#!/usr/bin/env python

from jira.client import JIRA

url = {'server': 'https://your.jira.instance'}

jira = JIRA(options=url, basic_auth=('user', 'password'))

issues = jira.search_issues('assignee=user and status=Open')

for issue in issues:
    print issue.key + '-' + issue.fields.issuetype.name + '-' + issue.fields.summary
